### ISSUE TITLE
No podemos subir archivos a nuestro propio repositorio

### ISSUE THREAD

**Issue by danmarsua1** [EGC-G2-Trabajo-1718/RedesSociales#1]
¿Es posible que esto se deba por el tipo de permiso que tiene asignado de solo lectura?

**Comment by robgc** [comment]
¿Seguís con este problema? Porque en principio todo el equipo tiene permisos de escritura. Si reabrís la incidencia dad más información al respecto, porque aparentemente tenéis los mismos permisos.

**Comment by danmarsua1** [comment]
Fallo mío Roberto, al no cerrarla. El problema estaba solucionado desde hace tiempo.

Gracias de todos modos por el interés. Cierro el hilo.
