### ISSUE TITLE
Widget para contactar a través de Twitter

### ISSUE THREAD

**Issue by juahueceb1** [EGC-G2-Trabajo-1718/RedesSociales#10]
**Prioridad:** medio.

**Descripción:**
Implementar un widget para crear un botón que permita enviar un mensaje directo a una cuenta de Twitter.

Documentación: https://dev.twitter.com/web/message-button

**Comment by luismiguelziuk** [comment]
He invertido 2 horas en estudio de la tecnologia GIT, para el cual estoy realizando el siguiente [curso](https://codigofacilito.com/cursos/git).

**Comment by luismiguelziuk** [comment]
He invertido 1 hora en la busqueda de posibles soluciones al problema.

**Comment by luismiguelziuk** [comment]
He invertido 2 hora en una reunion via skype con @crigalbla y @ruano23 para facilitar la compresion de la plantilla que se utiliza para la creacion de plugins.

Ademas se nos aclara el nuevo sistema de ramas, se crea nuestra propia rama y prepara la plantilla para el diseño del plugin.

**Comment by luismiguelziuk** [comment]
He invertido una 1 hora en la gestion del estilo del boton.

**Comment by luismiguelziuk** [comment]
He invertido 2 horas en las busqueda de un metodo para conseguir la ID de usuario de Twitter.

**Comment by luismiguelziuk** [comment]
He invertido 2 horas en dejar el plugin en fase beta y la realizacion de algunas pruebas funcionales de forma manual, comprobando su correcto funcionamiento. Quedando pendiente, de forma adicional y si fuera posible, la automatizacion de optencion del ID de cuenta de Twitter que utilizamos.

**Comment by luismiguelziuk** [comment]
Para la realizacion de dicha automatizacion se creara otra issue correspondiente a dicha tarea. Por tanto se da esta por cerrada.
