### ISSUE TITLE
Automatizar la construcción y el despliegue

### ISSUE THREAD

**Issue by juahueceb1** [EGC-G2-Trabajo-1718/RedesSociales#11]
**Prioridad:** media.

**Descripción:**
Automatizar la construcción y el despliegue del proyecto a través de Travis CI (https://travis-ci.org/).

**Comment by juahueceb1** [comment]
Hola @robgc.

Creé el fichero de configuración de Travis para nuestro subsistema (9e458def3c53d539498b99c9f59a1a8af4bd4283). Éste consiste en un plugin PHP, el cual debe ser alojado en el directorio wp-content/plugins de WordPress. He leído en la página de la wiki de la asignatura que habéis creado una plantilla para Travis. La he ojeado, pero he visto que está enfocada para el subsistema de votaciones. Quisiera saber qué estamos haciendo mal o qué debemos hacer antes de proceder a subir el plugin a master. Aún hay algunos issues por resolver.

Gracias.

**Comment by robgc** [comment]
Estamos investigando cómo automatizar la instalación de plugins en Wordpress, está siendo complicado debido a las diferencias entre subproyectos y a que solo puede haber una instancia de Wordpress con todos los plugins instalados. En cuanto tengamos avances haremos el anuncio por los medios correspondientes. Un saludo.
