### ISSUE TITLE
Rama 'luismiguel' duplicada

### ISSUE THREAD

**Issue by juahueceb1** [EGC-G2-Trabajo-1718/RedesSociales#14]
**Prioridad:** urgente.

**Descripción:**
La rama del desarrollador @luismiguelziuk está duplicada. Cada desarrollador sólo puede tener una rama. Commit afectado a43a05217fbd61b5acd9042543552c000b6382a4

**Comment by luismiguelziuk** [comment]
Por error en u comando de git no se intrujo bien el nombre de la rama por las mayusculas. Creandose un duplicado de ella. Se procede a borrar la rama que tiene mayusculas para evitar futuros errores iguales.

**Comment by luismiguelziuk** [comment]
Se ha eliminado la rama.

Se ha invertido 10 minutos en ello.
