### ISSUE TITLE
Compartir contenido en Telegram y WhatsApp

### ISSUE THREAD

**Issue by juahueceb1** [EGC-G2-Trabajo-1718/RedesSociales#15]
**Prioridad:** baja

**Descripción:**
Añadir dos botones más al widget #6: compartir contenido en Telegram y WhatsApp.

**Comment by luismiguelziuk** [comment]
Veo muy correcta esta peticion, son dos aplicaciones muy utiles ademas de ser las mas usadas para mensajeria directa. Si entra dentro del margen de tiempo que tenemos deberiamos desarrollarlo.

**Comment by juahueceb1** [comment]
A través del botón de Telegram se puede compartir la URL actual junto a un mensaje (opcional) que se puede configurar en el formulario del back-end de WordPress.

Tras hacer clic, se abre una nueva ventana donde se pide confirmación para compartir el contenido a través de la aplicación oficial si ésta estuviera instalada en el equipo.

![telegram](https://user-images.githubusercontent.com/32852855/34795653-4a5a58b6-f653-11e7-9d67-ca5d7c3a46ff.png)

**Comment by juahueceb1** [comment]
El botón para compartir contenido en WhatsApp solo funciona en dispositivos móviles; ya que requiere tener instalada la APP. Por ello, el botón se ocultará cuando no se esté visualizando la web en un dispositivo móvil (cuando el ancho de la pantalla sea menor de 768px).

**Comment by juahueceb1** [comment]
Se ha completado la tarea.

![telegram-whatsapp](https://user-images.githubusercontent.com/32852855/34820846-0945d48a-f6c2-11e7-9d37-564ebb78c70a.png)
