### ISSUE TITLE
Documentar apartados 2, 3 y 4 del documento del proyecto

### ISSUE THREAD

**Issue by juahueceb1** [EGC-G2-Trabajo-1718/RedesSociales#17]
**Prioridad:** media

**Descripción:**
Realizar tres apartados de la documentación del proyecto: “introducción y contexto”, “descripción del sistema” y “planificación del proyecto”.

Más información: https://github.com/EGCETSII/Entregables/wiki/Documento-del-proyecto

**Comment by crigalbla** [comment]
Se ha invertido un tiempo de 1 hora y 56 minutos para la realización de estos apartado. Aún quedan 2 pequeños detalles por terminar.

**Comment by crigalbla** [comment]
Se han terminado los apartados mencionados además de añadir mejoras. Se ha requerido de un tiempo de 1 hora y 12 minutos.

**Comment by crigalbla** [comment]
La actividad ha sido reabierta debido a un cierre erróneo.

**Comment by crigalbla** [comment]
Se han realizado algunos cambios. Tiempo invertido de 47 minutos.

**Comment by crigalbla** [comment]
Se han realizado mas cambios. Tiempo invertido de 36 minutos.

**Comment by crigalbla** [comment]
Se ha invertido 23 minutos más para acabar.
