### ISSUE TITLE
El widget timeline no funciona correctamente

### ISSUE THREAD

**Issue by juahueceb1** [EGC-G2-Trabajo-1718/RedesSociales#24]
**Prioridad:** urgente

**Descripción:**
No se muestra el timeline de Facebook. Sólo se muestra el timeline de Twitter. Además, éste aparece duplicado. Esta funcionalidad está asociada a la tarea #7 y al commit a959d5518efe222a9ef54c7aeb9aded5e92ffb89.
  
![issue-timeline](https://user-images.githubusercontent.com/32852855/34697124-fb377c8c-f4d1-11e7-977c-492fee79a0b4.png)

**Comment by ruano23** [comment]
El error se debía a que faltaba la etiqueta </a> en el timeline de Twitter, esto hacía que solo mostrara dicho timeline y dejará sin mostrar el timeline de facebook, una vez arreglado esto se muestran ambas correctamente.
