### ISSUE TITLE
Añadir un botón para ocultar los comentarios

### ISSUE THREAD

**Issue by juahueceb1** [EGC-G2-Trabajo-1718/RedesSociales#26]
**Prioridad:** baja

**Descripción:**
Añadir un botón para ocultar los comentarios de Facebook del widget #8.

**Comment by crigalbla** [comment]
Se ha estado investigando como ocultar solo los comentarios de widget. Debido a que usamos una API, no se puede editar el contenido, más concrétamente porque los "div" del código (viendolo en inspeccionar código con Google Chrome) no tienen IDs y el nombre de sus class empiezan por _
(la parte concreta de los comentarios tiene como nombre "_4k-6") esto quiere decir que no podemos ocultar ningún "div" ya que no podemos cogerlo. Por lo tanto se ha llegado a la conclusión de que se pondrá un botón para ocultarlo todo. 

Todo este trabajo ha requerido de 3 horas y 48 minutos. (A continuación el commit)
