### ISSUE TITLE
Añadir un timeline relacionado con un hashtag

### ISSUE THREAD

**Issue by juahueceb1** [EGC-G2-Trabajo-1718/RedesSociales#29]
**Prioridad:** baja

**Descripción:**
Añadir un timeline más para listar los tweets relacionados con un hashtag predeterminado para el widget #7.

**Comment by ruano23** [comment]
Depues de unas 3 horas mirando para poder añadir este timeline he logrado un codigo en el cual hay que pasarle un hashtag y un ID creado por el usuario en su cuenta de twitter para poder generar el widget. Con esto este timeline será mostrado.

**Comment by ruano23** [comment]
Se ha movido a "En progreso" ahora, pero llevo desde hace dos dias con esta issue.

**Comment by ruano23** [comment]
Doy por satisfecha esta issue.
