### ISSUE TITLE
Ficheros erróneos en la rama master

### ISSUE THREAD

**Issue by juahueceb1** [EGC-G2-Trabajo-1718/RedesSociales#3]
**Prioridad:** urgente.

**Descripción:**
Hay dos ficheros que aparecen en la rama principal (master): COMANDOS_GIT.docx (5e4f06e5ae7601bf6e8a899f3e99ea5e33cbcded) y redes_sociales_RSS.xml (efaf6d410cb6c245d59c0c96126396ea4f4bb9c3). Sin embargo, estos deberían aparecer en otras ramas porque no son entregables.

**Comment by danmarsua1** [comment]
Hola Juan,

en mi opinión, lo mejor sería quitarlos de la rama "master", ya que dijimos que esta rama debía estar limpia y unicamente contener las entregas finales.

Lo que se me ocurre en un principio, es quitar ambos archivos de la rama y mover el manual de word a la rama "develop" (aunque no sea archivo fuente de desarrollo, si que complementa esta tarea, pienso que debe mantenerse en el mismo lugar junto con el desarrollo del código). De la misma forma el archivo xml también debiera estar en la rama "develop", ya que es archivo fuente y además es parte del siguiente milestone.

**Comment by juahueceb1** [comment]
OK. Voy a proceder a hacer eso.

**Comment by juahueceb1** [comment]
Issue cerrado. Commits: 14e1bf88c11c4fe861926d3be2ba4af495e1e0c2, ef9eeb570b8fd67fb70f59880ed16f1357752696 y fb21527d4461529f9bab077d7add98c7ad01eb3a.
