### ISSUE TITLE
Modificaciones en el widget de mensajeria directa

### ISSUE THREAD

**Issue by juahueceb1** [EGC-G2-Trabajo-1718/RedesSociales#30]
**Prioridad:** baja

**Descripción:**
Añadir un mensaje por defecto al que se envía por Twitter en el widget #10. 
Añadido a 10/01/2018: Cambiar el tamaño del boton a uno mas pequeño para compartir la estetica. Ademas incluir un mensaje "Contact us by Twitter here" al widget.

**Comment by luismiguelziuk** [comment]
Investigo durante 1 hora como añadir esta funcionalidad y se decide añadir un formulario mas que genere un mensaje por defecto.

**Comment by luismiguelziuk** [comment]
Se ha invertido 45 minutos en la implementacion de dicha funcionalidad.

**Comment by luismiguelziuk** [comment]
Se habla con el grupo para incluir un mensaje encima del boton implementado y para cambiar el tamaño de dicho boton.

**Comment by albgomceb** [comment]
Encuentro un error en el mensaje del formulario del widget, en el cual pone massage en lugar de message y acoount en lugar de account.

**Comment by luismiguelziuk** [comment]
> Encuentro un error en el mensaje del formulario del widget, en el cual pone massage en lugar de message y acoount en lugar de account.

De acuerdo, lo corrijo y vuelvo a subirlo.

**Comment by luismiguelziuk** [comment]
He invertido 2 horas y 30 minutos en las modificaciones añadidas y en el repaso general del codigo dando esta issue por terminada.

**Comment by luismiguelziuk** [comment]
Cierro la issue.

**Comment by juahueceb1** [comment]
Para completar el widget de mensajería, se podría añadir un botón para comenzar una conversación en Hangout.

Más información: https://developers.google.com/+/hangouts/button

**Comment by luismiguelziuk** [comment]
Se han invertido 3 horas y media en la busqueda de informacion y en la implementacion de la funcionalidad de Hangouts, se realiza commit de la fase beta de dicha app para pruebas de los compañeros.

**Comment by ruano23** [comment]
He encontrado un error por el cual se muestra el boton de Hangouts aunque en el formulario no se introduzca una cuenta. Ademas añadir que el boton hangouts tiene un tamaño que choca a la vista con respecto al de Twitter.

**Comment by luismiguelziuk** [comment]
De acuerdo, me pongo a corregirlo cuando me sea posible y lo subo rectificado.

**Comment by luismiguelziuk** [comment]
Se invierte 30 minutos en la modificaciones. Quedando solucionados los problemas mencionados. Dando por finalizada la incidencia.

Cierro la issue.
