### ISSUE TITLE
Cambiar diseño feed RSS

### ISSUE THREAD

**Issue by juahueceb1** [EGC-G2-Trabajo-1718/RedesSociales#31]
**Prioridad:** baja

**Descripción:**
Cambiar el diseño del botón de la feed RSS del widget #9. Debe ser algo parecido a esto.

![images duckduckgo com](https://user-images.githubusercontent.com/32852855/34740298-32e3b1c0-f57f-11e7-9693-e9cf146addd7.png)

**Comment by albgomceb** [comment]
He cambiado el icono existente por el apropiado para la web.

**Comment by albgomceb** [comment]
Debido a un fallo cometido por mi, la rama no partía de "develop" sino que lo hacia de "master". Por lo tanto, he borrado mi rama y reabierto otra. Reabro la issue y vuelvo a subir el widget para cambiar hacia el icono apropiado para la web.
