### ISSUE TITLE
Configurar el número de mensajes y el color del fondo

### ISSUE THREAD

**Issue by juahueceb1** [EGC-G2-Trabajo-1718/RedesSociales#32]
**Prioridad:** baja

**Descripción:**
Habilitar dos opciones en el formulario de configuración del widget #8: cambiar el número de mensajes que aparecen por defecto y el color del fondo.

**Comment by crigalbla** [comment]
En cuanto a la configuración del número de mensajes ya se ha realizado. Todo el trabajo de esta issue ha requerido de algo más de 2 horas.
