### ISSUE TITLE
Añadir opciones de personalización para un timeline

### ISSUE THREAD

**Issue by juahueceb1** [EGC-G2-Trabajo-1718/RedesSociales#34]
**Prioridad:** baja

**Descripción:**
Añadir opciones de personalización (tamaño, número de publicaciones y bordes) de los timelines creados en el widget #7 en el formulario de configuración.

**Comment by ruano23** [comment]
Despues de 3 horas indagando en la personalizacion de dichos timeline:
-He podido poner personalizacion al timeline de facebook
-No se pueden añadir personalizaciones al timeline de los hashtag porque son personificados en el perfil de cada usuario de twitter.

**Comment by ruano23** [comment]
He conseguido añadir la personalizacion de twitter y con esto la doy por cerrada.
