### ISSUE TITLE
Crear un shortcode para la caja de comentarios

### ISSUE THREAD

**Issue by juahueceb1** [EGC-G2-Trabajo-1718/RedesSociales#35]
**Prioridad:** baja.

**Descripción:**
Crear un shortcode que permita insertar la caja de comentarios del widget #8  dentro de un artículo de WordPress.

Más información: https://codex.wordpress.org/Shortcode_API

**Comment by crigalbla** [comment]
Se ha terminado el trabajo, el tiempo de desempeño ha sido de 1 hora y 42 minutos.
