### ISSUE TITLE
Error en el formulario de configuración del widget de los comentarios

### ISSUE THREAD

**Issue by juahueceb1** [EGC-G2-Trabajo-1718/RedesSociales#36]
**Prioridad:** media.

**Descripción:**
En el formulario de configuración del widget de los comentarios hay un error: se trata del parámetro "Num of comments", cuando introduces un número menor que 1 o cualquier otro valor no numérico, el widget no se muestra correctamente. Commit afectado: ff2aaa7b64dee186c5de4d2a27e5a3ee5e2ea4c9

**Comment by crigalbla** [comment]
Se va a revisar el código afectado.

**Comment by crigalbla** [comment]
El problema era debido a que no se controlaban parámetros no numéricos. Además tampoco se tenía en cuenta valores menos de 1.
