### ISSUE TITLE
Widget para seguir los perfiles en redes sociales

### ISSUE THREAD

**Issue by danmarsua1** [EGC-G2-Trabajo-1718/RedesSociales#4]
**Prioridad:** medio.

**Descripción:**
Implementar un widget que integre los botones de "Me gusta/Seguir" para la redes sociales de Twitter, Facebook, Google+, Instagram y LinkedIn.

**Comment by juahueceb1** [comment]
Aún faltan funcionalidades por implementar.

**Comment by danmarsua1** [comment]
Tarea terminada. He invertido cerca de 2 días aproximadamente en desarrollar un plugin para Wordpress que reuniera la funcionalidad de seguimiento de cada red social y que cada cuenta se pudiera modificar por el usuario consumidor del plugin.
