### ISSUE TITLE
Automatizar las pruebas del widget para seguir los perfiles en redes sociales

### ISSUE THREAD

**Issue by juahueceb1** [EGC-G2-Trabajo-1718/RedesSociales#44]
**Prioridad:** alta

**Descripción:**
Implementar las pruebas necesarias para comprobar que el widget para seguir los perfiles en redes sociales funciona correctamente y automatizar éstas con Travis CI. Para ello, se comprobará que el widget se encuentra registrado correctamente en WordPress y que la función _getUsername_ devuelve un nombre de usuario con el formato adecuado.

**Comment by danmarsua1** [comment]
Tarea terminada. Procedo a cerrar la incidencia.
