### ISSUE TITLE
Automatizar las pruebas del widget para comentarios

### ISSUE THREAD

**Issue by juahueceb1** [EGC-G2-Trabajo-1718/RedesSociales#46]
**Prioridad:** alta

**Descripción:**
Implementar las pruebas necesarias para comprobar que el widget para comentarios funciona correctamente y automatizar éstas con Travis CI. Para ello, se implementarán varios tests:

- Comprobar que el widget se encuentra registrado correctamente en WordPress.
- Comprobar las diferentes opciones de configuración de los estilos del widget.

**Comment by crigalbla** [comment]
Se ha terminado esta tarea.
