### ISSUE TITLE
Automatizar las pruebas del widget de mensajería

### ISSUE THREAD

**Issue by juahueceb1** [EGC-G2-Trabajo-1718/RedesSociales#47]
**Prioridad:** alta

**Descripción:**
Implementar las pruebas necesarias para comprobar que el widget de mensajería funciona correctamente y automatizar éstas con Travis CI. Además, se comprobará que el widget se encuentra registrado correctamente en WordPress.

**Comment by danmarsua1** [comment]
Tarea terminada. Procedo a cerrar la incidencia.
