### ISSUE TITLE
Automatizar las pruebas del widget para generar feed RSS

### ISSUE THREAD

**Issue by juahueceb1** [EGC-G2-Trabajo-1718/RedesSociales#49]
**Prioridad:** alta

**Descripción:**
Implementar las pruebas necesarias para comprobar que el widget para generar feed RSS funciona correctamente y automatizar éstas con Travis CI. Para ello, se implementarán varios tests:

- Comprobar que el widget se encuentra registrado correctamente en WordPress.
- Comprobar que la función que comprueba la activación y desactivación de los botones de RSS, Flipboard y Feedly funciona correctamente.

**Comment by albgomceb** [comment]
He realizado el fichero para la automatización de pruebas. Para ello compruebo que el widget esta registrado en WordPress, que se encuentre activo y que funcione correctamente el constructor.

**Comment by albgomceb** [comment]
He abierto de nuevo la Issue debido a un fallo de codificación y para proceder a realizar otros test más concretos con la funcionalidad desarrollada.

**Comment by albgomceb** [comment]
He realizado dos test que comprueban los métodos estáticos del widget realizado con anterioridad. Ambos test han pasado la prueba con Travis-CI. Cierro el issue.
