### ISSUE TITLE
Implementación de plugin para WordPress

### ISSUE THREAD

**Issue by danmarsua1** [EGC-G2-Trabajo-1718/RedesSociales#5]
**Prioridad:** alta.

**Descripción:**
Se desea implementar un plugin en Wordpress que contenga las funcionalidades de cada red social que tenemos asignadas en este proyecto: Twitter, Facebook, Instagram, LinkedIn, Reddit y Google+.

Estas funcionalidades deben estar funcionando conjuntamente para hacer más sencilla y eficaz la instalación, en lugar de tener que instalar plugins por cada red social.

**Comment by juahueceb1** [comment]
He reabierto esta tarea por varios motivos:
- Cambiar el título de la misma.
- Adaptar la descripción de la misma al formato que hemos acordado.
- Modularizar el plugin para que todas las funcionalidades no estén en el fichero principal PHP.

**Comment by juahueceb1** [comment]
Se han añadido dos funciones al fichero principal:

- load_widgets_EGC: carga los widgets de las redes sociales a integrar (compartir contenido, seguir a un perfil, caja de comentarios, embeber timeline…).
- include_API_EGC: incluye las APIs de las redes sociales, que son necesarias para el buen funcionamiento de los widgets.
