### ISSUE TITLE
Widget para timelines

### ISSUE THREAD

**Issue by juahueceb1** [EGC-G2-Trabajo-1718/RedesSociales#7]
**Prioridad:** medio.

**Descripción:**
Implementar un widget que permita embeber timelines (una secuencia de publicaciones ordenadas cronológicamente) para las redes sociales Twitter, Facebook, Instagram y Google+.

Documentación:
- Twitter: https://dev.twitter.com/web/embedded-timelines
- Facebook: https://developers.facebook.com/docs/plugins/embedded-posts
- Instagram: https://www.instagram.com/developer/embedding
- Google+: https://developers.google.com/+/web/embedded-post

**Comment by ruano23** [comment]
He invertido 2 hora en una reunion via skype con @crigalbla y @luismiguelziuk  para facilitar la compresion de la plantilla que se utiliza para la creacion de plugins.

Ademas se nos aclara el nuevo sistema de ramas, se crea nuestra propia rama y prepara la plantilla para el diseño del plugin.

**Comment by ruano23** [comment]
He invertido 2 horas en investigar la forma de añadir los timelines.

**Comment by ruano23** [comment]
Despues de unos días he decidido no meter el timeline de instagram por su costoso trabajo. Mantenemos facebook, twitter y google+.

**Comment by ruano23** [comment]
Con la documentacion que nos aporta google+, https://developers.google.com/+/web/embedded-post/ no se puede realizar el embebido, supongo que por alguna actualización. No se puede coger el codigo del post.

**Comment by ruano23** [comment]
He invertido 3 horas en arreglo del codigo para el funcionamiento del widget.
