### ISSUE TITLE
Widget para comentarios

### ISSUE THREAD

**Issue by juahueceb1** [EGC-G2-Trabajo-1718/RedesSociales#8]
**Prioridad:** medio.

**Descripción:**
Implementar un widget para insertar comentarios en una publicación. Los usuarios usarán su cuenta de Facebook para poder comentar.

Documentación: https://developers.facebook.com/docs/plugins/comments

**Comment by crigalbla** [comment]
El trabajo realizado en el commit anterior
( https://github.com/EGC-G2-Trabajo-1718/RedesSociales/commit/4c36ee77754f35925681eb177571b12cd00e51bd ) ha requerido de 3 horas y 50 minutos.

**Comment by crigalbla** [comment]
Se ha realizado un trabajo de 3 horas y 14 minutos para estudiar la forma de añadir los moderadores. Ya está casi listo.

**Comment by crigalbla** [comment]
Finalmente me he percatado de que la herramienta de moderación no puede ser añadido usando una máquina local. Para ello es necesario una aplicación de Facebook (requiere de un procedimiento de creación) y una URL de la página donde está la caja de comentarios. Siendo esto último lo que nos falla y por lo tanto no podemos probar.
