### ISSUE TITLE
Widget para generar feed RSS

### ISSUE THREAD

**Issue by juahueceb1** [EGC-G2-Trabajo-1718/RedesSociales#9]
**Prioridad:** medio.

**Descripción:**
Implementar un widget para insertar un botón que genere un archivo RSS para poder seguir las publicaciones de la web.

**Comment by albgomceb** [comment]
He invertido 1 hora 20 minutos en obtener información acerca de la tecnología RSS y como implementar el plugin.

**Comment by albgomceb** [comment]
He finalizado la creación del widget para mostrar el contenido RSS.
